### ISSUE TITLE
Hard coded library path breaks on 64 bit system

### ISSUE THREAD

**Issue by mjskier** [kreynolds/phidgets-ffi#2]
When compiling/installing the libphidget library on an OpenSuse 12.1 64 bit system the library ends up being installed in /usr/lib64, not /usr/lib.
So this in lib/phidgets-ffi/phidgets-ffi.rb breaks:

```
else # Linux
  ffi_lib '/usr/lib/libphidget21.so'
end
```

/usr/lib64/ruby/gems/1.8/gems/ffi-1.0.11/lib/ffi/library.rb:121:in `ffi_lib': Could not open library '/usr/lib/libphidget21.so': /usr/lib/libphidget21.so: cannot open shared object file: No such file or directory (LoadError)
        from /usr/lib64/ruby/gems/1.8/gems/ffi-1.0.11/lib/ffi/library.rb:88:in`map'
...
...

I don't have my stepper controller yet so I can't test if anything is else is broken on a 64 bit system, but doing a symbolic link from /usr/lib64/libphidget21.so to /usr/lib/libphidget21.so goes past that error.

**Comment by mjskier** [comment]
Looks like lib/phidgets-ffi/ffi/manager.rb would has the same issue.

**Comment by mphi** [comment]
Thanks for letting us know. 

I have modified /lib/phidgets-ffi/phidgets-ffi.rb to handle situations where the libphidget21.so is installed in a directory other than /usr/lib.
commit 56ff200e9972b8042d3092d4a238f7ce2898e41b

I do not have a 64 bit version of OpenSuse, so I am not able to test the changes.

**Comment by mjskier** [comment]
I did some investigation/testing and all the linux related cases could be replaced with this one line:

  ffi_lib ['phidget21', '/Library/Frameworks/Phidget21.framework/Versions/Current/Phidget21', '/usr/lib64', '/usr/lib']

I can't test but it is possible that would work on darwin too (I don't have a Mac so I can't try)

Thanks so much for putting this interface together BTW

**Comment by mphi** [comment]
No, problem. It was our pleasure in putting up the Ruby interface for Phidgets.

I agree, your way is a better method for finding the Phidget drivers. I have applied the changes to /lib/phidgets-ffi/phidgets-ffi.rb

**Comment by kreynolds** [comment]
@mphi if you can test the simplified loading across a few platforms, I'll release a new gem version with the updates.

**Comment by mjskier** [comment]
One other potential issue is this code in manager.rb: It looks like this is used to store an array of pointers?
On a 64 bit Linux that should also be 8 bytes.
Maybe this can be simplified like this. Obviously need to test on a 32 bit system and Mac.

FFI_POINTER_SIZE = 1.size.size

(Give me the size of the size function from the class integer) There might be a better way, but on my 64bit machine this returns 8.

if Config::CONFIG['target_os'] =~ /darwin/ #Mac OS X
        FFI_POINTER_SIZE = 4  
else  #Linux
        FFI_POINTER_SIZE = 8  
end

**Comment by kreynolds** [comment]
@mjskier can you open up a new issue relating to pointer sizing and attach any test results/new code there?

**Comment by mjskier** [comment]
Will do. 
I'm going to wait for my phidget to show up to see if this is indeed an issue. Hopefully this week.

**Comment by mphi** [comment]
FFI_POINTER_SIZE = 1.size works on my Mac 32 bit system. It returns 4. 

I am not sure I understand why you need to take the size of the size of the Integer class, rather than just taking the size of the Integer class. In both situations, 4 is returned.

**Comment by kreynolds** [comment]
You don't need to take the size twice.

**Comment by mphi** [comment]
@kreynolds I tested commit: 56ff200e99 under multiple environments and the library runs fine.

**Comment by mjskier** [comment]
It looks like this constant is used for pointer arithmetic?
I assume you want a pointer size, not an integer size since these are not guaranteed to be the same size.

My train of thought was:
1.size would give you the size of an integer.
1.size.size would give you the size of the pointer to the integer function for the integer class. (would it, or does it just give you 4.size  or 8.size...)

**Comment by mjskier** [comment]
This might be helpful: http://rubydoc.info/github/ffi/ffi/master/FFI/Pointer
I can't try it right now, but it look like there should be a FFI::Platform::ADDRESS_SIZE

**Comment by kreynolds** [comment]
Size -> Fixnum
"Returns the number of bytes in the machine representation of a Fixnum."

There is no difference between 1.size and 1.size.size.size.size.size.size.size.size.

**Comment by mjskier** [comment]
and here I was thinking I had found a clever hack. Thanks for dashing my hopes of greatness.
